Fix message of invalid option managing requests
The program used to say "skipping this request" which is not accurate,
since the user can try again.

Request from: eve
1. Accept
2. Reject
Enter your choice: g

ERROR: Invalid choice, skipping this request.

Request from: eve
1. Accept
2. Reject